name: Release Extension

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Create .env file
        run: |
          echo "API_URL=${{ vars.API_URL }}" >> .env
          echo "INTRANET_ORIGIN=${{ vars.INTRANET_ORIGIN }}" >> .env
          echo "WEB_URL=${{ vars.WEB_URL }}" >> .env
          echo "LOGIN_URL=${{ vars.LOGIN_URL }}" >> .env
          echo "ACCESS_TOKEN_COOKIE_NAME=${{ vars.ACCESS_TOKEN_COOKIE_NAME }}" >> .env
          echo "USER_DEFAULT_IMAGE=${{ vars.USER_DEFAULT_IMAGE }}" >> .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "SENTRY_ENABLED=true" >> .env

      - name: Build Extension
        run: |
          npm install -D
          npm install -D webpack-cli
          npm run build
          npm run pack
        env:
          NODE_ENV: production
          SENTRY_ENABLED: true

      - name: Upload To Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: release/Alexis-*.zip
          extension-id: ${{ vars.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          glob: true
